/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Com.edusys.ui;

import Com.edusys.model.KhoaHoc;
import Com.edusys.utility.DialogHelper;
import Com.edusys.utility.ShareHelper;
import Com.edusys.utility.Xlimage;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author ADMIN
 */
public class View_EduSys extends javax.swing.JFrame {

    /**
     * Creates new form View_EduSys
     */
    public View_EduSys() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btn_logout = new javax.swing.JButton();
        btn_end = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btn_chuyende = new javax.swing.JButton();
        btn_nguoihoc = new javax.swing.JButton();
        btn_khoahoc = new javax.swing.JButton();
        btn_hocvien = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btn_huongdan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_quanly = new javax.swing.JLabel();
        lbl_time = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnu_hethong = new javax.swing.JMenu();
        mni_login = new javax.swing.JMenuItem();
        mni_logout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mni_changepass = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mni_end = new javax.swing.JMenuItem();
        mnu_quanly = new javax.swing.JMenu();
        mni_chuyende = new javax.swing.JMenuItem();
        mni_khoahoc = new javax.swing.JMenuItem();
        mni_nguoihoc = new javax.swing.JMenuItem();
        mni_hocvien = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mni_nhanvien = new javax.swing.JMenuItem();
        mnu_thongke = new javax.swing.JMenu();
        mni_diem = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mni_songuoihoc = new javax.swing.JMenuItem();
        mni_diemchuyende = new javax.swing.JMenuItem();
        mni_doanhthu = new javax.swing.JMenuItem();
        mnu_help = new javax.swing.JMenu();
        mni_huongdan = new javax.swing.JMenuItem();
        mni_gioithieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("  HỆ QUẢN LÝ ĐÀO TẠO");

        jToolBar1.setRollover(true);

        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/edusys/icon/Log out.png"))); // NOI18N
        btn_logout.setText("Đăng Xuất");
        btn_logout.setFocusable(false);
        btn_logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_logout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_logout);

        btn_end.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/edusys/icon/Stop.png"))); // NOI18N
        btn_end.setText("Kết thúc");
        btn_end.setFocusable(false);
        btn_end.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_end.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_end.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_endActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_end);

        jSeparator5.setBackground(new java.awt.Color(51, 51, 51));
        jToolBar1.add(jSeparator5);

        btn_chuyende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/edusys/icon/Lists.png"))); // NOI18N
        btn_chuyende.setText("Chuyên đề");
        btn_chuyende.setFocusable(false);
        btn_chuyende.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_chuyende.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_chuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chuyendeActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_chuyende);

        btn_nguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/edusys/icon/Clien list.png"))); // NOI18N
        btn_nguoihoc.setText("Người học");
        btn_nguoihoc.setFocusable(false);
        btn_nguoihoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_nguoihoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_nguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nguoihocActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_nguoihoc);

        btn_khoahoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/edusys/icon/Certificate.png"))); // NOI18N
        btn_khoahoc.setText("Khóa học");
        btn_khoahoc.setFocusable(false);
        btn_khoahoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_khoahoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_khoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_khoahocActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_khoahoc);

        btn_hocvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/edusys/icon/User.png"))); // NOI18N
        btn_hocvien.setText("Học viên");
        btn_hocvien.setFocusable(false);
        btn_hocvien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_hocvien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_hocvien);
        jToolBar1.add(jSeparator6);

        btn_huongdan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/edusys/icon/Help.png"))); // NOI18N
        btn_huongdan.setText("Hướng dẫn");
        btn_huongdan.setFocusable(false);
        btn_huongdan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_huongdan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_huongdan);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/edusys/icon/logo-small.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        lbl_quanly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/edusys/icon/Info.png"))); // NOI18N
        lbl_quanly.setText("Hệ quản lý đào tạo");

        mnu_hethong.setText("Hệ Thống");

        mni_login.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mni_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/edusys/icon/Login.png"))); // NOI18N
        mni_login.setText("Đăng Nhập");
        mnu_hethong.add(mni_login);

        mni_logout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mni_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/edusys/icon/Log out.png"))); // NOI18N
        mni_logout.setText("Đăng Xuất");
        mni_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_logoutActionPerformed(evt);
            }
        });
        mnu_hethong.add(mni_logout);
        mnu_hethong.add(jSeparator1);

        mni_changepass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/edusys/icon/Refresh.png"))); // NOI18N
        mni_changepass.setText("Đổi mật khẩu");
        mni_changepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_changepassActionPerformed(evt);
            }
        });
        mnu_hethong.add(mni_changepass);

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        mnu_hethong.add(jSeparator2);

        mni_end.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        mni_end.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/edusys/icon/Delete.png"))); // NOI18N
        mni_end.setText("Kết Thúc");
        mnu_hethong.add(mni_end);

        jMenuBar1.add(mnu_hethong);

        mnu_quanly.setText("Quản lý");

        mni_chuyende.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mni_chuyende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/edusys/icon/Lists.png"))); // NOI18N
        mni_chuyende.setText("Chuyên đề");
        mni_chuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_chuyendeActionPerformed(evt);
            }
        });
        mnu_quanly.add(mni_chuyende);

        mni_khoahoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mni_khoahoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/edusys/icon/Certificate.png"))); // NOI18N
        mni_khoahoc.setText("Khóa học");
        mni_khoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_khoahocActionPerformed(evt);
            }
        });
        mnu_quanly.add(mni_khoahoc);

        mni_nguoihoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mni_nguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/edusys/icon/Clien list.png"))); // NOI18N
        mni_nguoihoc.setText("Người học");
        mni_nguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_nguoihocActionPerformed(evt);
            }
        });
        mnu_quanly.add(mni_nguoihoc);

        mni_hocvien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mni_hocvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/edusys/icon/User.png"))); // NOI18N
        mni_hocvien.setText("Học Viên");
        mnu_quanly.add(mni_hocvien);
        mnu_quanly.add(jSeparator3);

        mni_nhanvien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mni_nhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/edusys/icon/User group.png"))); // NOI18N
        mni_nhanvien.setText("Nhân Viên");
        mni_nhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_nhanvienActionPerformed(evt);
            }
        });
        mnu_quanly.add(mni_nhanvien);

        jMenuBar1.add(mnu_quanly);

        mnu_thongke.setText("Thống kê");

        mni_diem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mni_diem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/edusys/icon/Open letter.png"))); // NOI18N
        mni_diem.setText("Bảng điểm");
        mni_diem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_diemActionPerformed(evt);
            }
        });
        mnu_thongke.add(mni_diem);
        mnu_thongke.add(jSeparator4);

        mni_songuoihoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mni_songuoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/edusys/icon/Conference.png"))); // NOI18N
        mni_songuoihoc.setText("Lượng người học");
        mni_songuoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_songuoihocActionPerformed(evt);
            }
        });
        mnu_thongke.add(mni_songuoihoc);

        mni_diemchuyende.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mni_diemchuyende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/edusys/icon/Documents.png"))); // NOI18N
        mni_diemchuyende.setText("Điểm chuyên đề");
        mni_diemchuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_diemchuyendeActionPerformed(evt);
            }
        });
        mnu_thongke.add(mni_diemchuyende);

        mni_doanhthu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mni_doanhthu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/edusys/icon/Dollar.png"))); // NOI18N
        mni_doanhthu.setText("Doanh thu");
        mni_doanhthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_doanhthuActionPerformed(evt);
            }
        });
        mnu_thongke.add(mni_doanhthu);

        jMenuBar1.add(mnu_thongke);

        mnu_help.setText("Trợ Giúp");

        mni_huongdan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mni_huongdan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/edusys/icon/Help.png"))); // NOI18N
        mni_huongdan.setText("Hướng dẫn sử dụng");
        mnu_help.add(mni_huongdan);

        mni_gioithieu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        mni_gioithieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/edusys/icon/Globe.png"))); // NOI18N
        mni_gioithieu.setText("Giới thiệu hệ thống");
        mni_gioithieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_gioithieuActionPerformed(evt);
            }
        });
        mnu_help.add(mni_gioithieu);

        jMenuBar1.add(mnu_help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_quanly)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_time, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_quanly)
                    .addComponent(lbl_time))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mni_chuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_chuyendeActionPerformed
        new QuanLyChuyenDe().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_mni_chuyendeActionPerformed

    private void mni_nguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_nguoihocActionPerformed
        new NguoiHocj().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_mni_nguoihocActionPerformed

    private void mni_gioithieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_gioithieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mni_gioithieuActionPerformed

    private void btn_endActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_endActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_endActionPerformed

    private void mni_nhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_nhanvienActionPerformed
        new NhanVien().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_mni_nhanvienActionPerformed

    private void btn_chuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chuyendeActionPerformed
        new QuanLyChuyenDe().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_chuyendeActionPerformed

    private void mni_changepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_changepassActionPerformed
       new DoiMatKhau().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_mni_changepassActionPerformed

    private void mni_diemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_diemActionPerformed
      new ThongKE(0).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_mni_diemActionPerformed

    private void mni_songuoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_songuoihocActionPerformed
       new ThongKE(1).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_mni_songuoihocActionPerformed

    private void mni_diemchuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_diemchuyendeActionPerformed
       new ThongKE(2).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_mni_diemchuyendeActionPerformed

    private void mni_doanhthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_doanhthuActionPerformed
      new ThongKE(3).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_mni_doanhthuActionPerformed

    private void btn_nguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nguoihocActionPerformed
        new NguoiHocj().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btn_nguoihocActionPerformed

    private void btn_khoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_khoahocActionPerformed
       new ChuyenDe().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_khoahocActionPerformed

    private void mni_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_logoutActionPerformed
       new DangNhap().setVisible(true);
       this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_mni_logoutActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        new DangNhap().setVisible(true);
       this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void mni_khoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_khoahocActionPerformed
       new ChuyenDe().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_mni_khoahocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_EduSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_EduSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_EduSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_EduSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_EduSys().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_chuyende;
    private javax.swing.JButton btn_end;
    private javax.swing.JButton btn_hocvien;
    private javax.swing.JButton btn_huongdan;
    private javax.swing.JButton btn_khoahoc;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_nguoihoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbl_quanly;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JMenuItem mni_changepass;
    private javax.swing.JMenuItem mni_chuyende;
    private javax.swing.JMenuItem mni_diem;
    private javax.swing.JMenuItem mni_diemchuyende;
    private javax.swing.JMenuItem mni_doanhthu;
    private javax.swing.JMenuItem mni_end;
    private javax.swing.JMenuItem mni_gioithieu;
    private javax.swing.JMenuItem mni_hocvien;
    private javax.swing.JMenuItem mni_huongdan;
    private javax.swing.JMenuItem mni_khoahoc;
    private javax.swing.JMenuItem mni_login;
    private javax.swing.JMenuItem mni_logout;
    private javax.swing.JMenuItem mni_nguoihoc;
    private javax.swing.JMenuItem mni_nhanvien;
    private javax.swing.JMenuItem mni_songuoihoc;
    private javax.swing.JMenu mnu_help;
    private javax.swing.JMenu mnu_hethong;
    private javax.swing.JMenu mnu_quanly;
    private javax.swing.JMenu mnu_thongke;
    // End of variables declaration//GEN-END:variables

    private void init() {
        this.setLocationRelativeTo(null);
        this.setIconImage(Xlimage.getAppIcon());
        new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date now = new Date();
                SimpleDateFormat formater = new SimpleDateFormat("hh::mm:ss a");
                String text = formater.format(now);
                lbl_time.setText(text);
            }
        }).start();
    }

    void openLogin() {
        new DangNhap().setVisible(true);
    }

    void openWelcome() {
        new ChaoEduSys().setVisible(true);
    }

    void exit() {

        if (DialogHelper.confirm(this, "Bạn thực sự muốn kết thúc?")) {
            System.exit(0);
        }
    }
    Integer ind0 = 0;
    Integer ind1 = 0;
    Integer ind2 = 0;
    Integer ind3 = 0;
    ThongKE thtk0 = new ThongKE(0);
    ThongKE thtk1 = new ThongKE(1);
    ThongKE thtk2 = new ThongKE(2);
    ThongKE thtk3 = new ThongKE(3);

    void openThongKe(int index) {

        if (ShareHelper.authenticated()) {
            if (index == 0) {
                if (ind0 == 0) {
                    thtk0.setVisible(true);
                    ind0 = 1;
                }
                if (ind0 == 1) {
                    thtk0.dispose();
                    thtk0.setVisible(true);
                }
            }
            if (index == 1) {
                if (ind1 == 0) {
                    thtk1.setVisible(true);
                    ind1 = 1;
                }
                if (ind1 == 1) {
                    thtk1.dispose();
                    thtk1.setVisible(true);
                }
            }
            if (index == 2) {
                if (ind2 == 0) {
                    thtk2.setVisible(true);
                    ind2 = 1;
                }
                if (ind2 == 1) {
                    thtk2.dispose();
                    thtk2.setVisible(true);
                }
            }
            if (index == 3) {
                if (ind3 == 0) {
                    thtk3.setVisible(true);
                    ind3 = 1;
                }
                if (ind3 == 1) {
                    thtk3.dispose();
                    thtk3.setVisible(true);
                }
            }

        } else {
            DialogHelper.alert(this, "Vui lòng đăng nhập!");
        }
    }
    KhoaHoc qlkh = new KhoaHoc();

    void openKhoaHoc() {
        if (ShareHelper.authenticated()) {
            if (qlkh == null) {
                qlkh.setVisible(true);
            } else {
                qlkh.dispose();
                qlkh.setVisible(true);
            }
        } else {
            DialogHelper.alert(this, "Vui lòng đăng nhập!");
        }
    }
    QuanLyChuyenDe qlcd = new QuanLyChuyenDe();

    void openChuyenDe() {
        if (ShareHelper.authenticated()) {
            if (qlcd == null) {
                qlcd.setVisible(true);
            } else {
                qlcd.dispose();
                qlcd.setVisible(true);
            }
        } else {
            DialogHelper.alert(this, "Vui lòng đăng nhập!");
        }
    }

    void openNguoiHoc() {
        if (ShareHelper.authenticated()) {

            new QuanLy().setVisible(true);
        } else {
            DialogHelper.alert(this, "Vui lòng đăng nhập!");
        }
    }

    void openAbout() {
        new ChaoEduSys().setVisible(true);
    }
}
